USE sucos_vendas

SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO $$$'
	WHEN PRECO_DE_LISTA >= 8 AND PRECO_DE_LISTA < 12 THEN 'PRECO JUSTO =)'
	WHEN PRECO_DE_LISTA >= 5 AND PRECO_DE_LISTA < 8 THEN 'PRECINHO =D'
	ELSE 'PREJÚ =(' END AS FAIXAS_DE_PREÇOS FROM tabela_de_produtos;
    
    
    SELECT EMBALAGEM, 
CASE
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO $$$'
	WHEN PRECO_DE_LISTA >= 8 AND PRECO_DE_LISTA < 12 THEN 'PRECO JUSTO =)'
	WHEN PRECO_DE_LISTA >= 5 AND PRECO_DE_LISTA < 8 THEN 'PRECINHO =D'
	ELSE 'PREJÚ =('
    END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
    FROM tabela_de_produtos
    WHERE SABOR = 'MANGA'
GROUP BY EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO $$$'
	WHEN PRECO_DE_LISTA >= 8 AND PRECO_DE_LISTA < 12 THEN 'PRECO JUSTO =)'
	WHEN PRECO_DE_LISTA >= 5 AND PRECO_DE_LISTA < 8 THEN 'PRECINHO =D'
	ELSE 'PREJÚ =('
    END
    ORDER BY EMBALAGEM
