SELECT LTRIM('    OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ    ') AS RESULTADO;

SELECT TRIM('    OLÁ    ') AS RESULTADO;

SELECT concat('Olá',' ','Mundo!!!') AS RESULTADO;

SELECT ucase(concat('Olá',' ','Mundo!!!')) AS RESULTADO;

SELECT SUBSTRING('Olá Mundo!!!', 4,9) AS RESULTADO;

SELECT CONCAT(NOME,' (CPF: ',CPF,') (',IDADE,' ANOS)') AS CLIENTE FROM tabela_de_clientes ORDER BY IDADE DESC;

SELECT CONCAT(NOME,'; ',ENDERECO_1,'; ',BAIRRO,'; ',CIDADE,'; ',ESTADO) AS CLIENTE_POR_NOME_E_ENDEREÇO FROM tabela_de_clientes 
ORDER BY IDADE;

