select * from tbcliente;

select CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
from tbcliente;

select CPF, NOME, ESTADO, SEXO
from tbcliente;

select CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE, ENDERECO1 AS ENDERECO_RESIDENCIAL, ENDERECO2 AS ENDERECO_COMERCIAL
from tbcliente LIMIT 5;

